
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: room_booking_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_DB=room_booking_db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST=db
    depends_on:
      - db
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - web

volumes:
  postgres_data:
